version: "3"

services:
  application:
    build: "./application"
    container_name: "application"
    ports:
      - "8080:8080"
  web:
    image: "nginx:1.23.1-alpine"
    ports:
      - "80:80"
    volumes:
      - "./nginx/vol/html:/usr/share/nginx/html"
      - "./nginx/vol/conf.d:/etc/nginx/conf.d"
    depends_on:
      - application



