version: "3"

services:
  application:
    build: "./application"
    container_name: "application"
    ports:
      - "5000:8080"
  web:
    image: "nginx:1.23.1-alpine"
    ports:
      - "80:80"
    container_name: "nginx_web"
    volumes:
      - "./nginx/vol/html:/usr/share/nginx/html"



