version: "3"

services:
  application:
    build: "./application"
    ports:
      - "8080:8080"
  web:
    image: "nginx:1.23.1-alpine"
    ports:
      - "80:80"
    volumes:
      - "./nginx/vol/html:/usr/share/nginx/html"
      - "./nginx/vol/conf.d:/etc/nginx/conf.d"
    depends_on:
      - application
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8081:8080"
    volumes:
      - "./jenkins/vol/var/run/docker.sock:/var/run/docker.sock"
      - "./jenkins/vol/var/jenkins_home:/var/jenkins_home"
    user: root
    privileged: true
